### ISSUE TITLE
Solicitud desplazamiento imagen ISII a BDI

### ISSUE THREAD

**Issue by MavapeGZ** [StephanJ98/Univ_Codes#1]
Esta imagen corresponde a BDI, no a ISII

**Comment by MavapeGZ** [comment]
> > Esta imagen corresponde a BDI, no a ISII
> 
> @MavapeGZ Vas a tener que especificar a qué imagen te refieres, al menos proporcionar una URL.

https://github.com/StephanJ98/Univ_Codes/blob/main/ISII/2020_21/Entidades%20debiles.png

**Comment by StephanJ98** [comment]
@MavapeGZ  Corregido con los commits [ 00e39de92a3b6d2b7e350d65f756638d93d6ece6, 1c1c1955f18bba8e0936cb68a7cd9f0e443724e5 ].
